### PR TITLE
Refactor/code cleanup

### PR DESCRIPTION
**Pull request by girotobial**
These are the changes I made on my own personal fork, based on progressive_zl. 

Safe to say they don't work yet (config load fails), but I think it's a good start.

### CODE REVIEW

**Comment by girotobial** [comment]
@artesim any thoughts on this? I'm unsure whether to proceed with this branch.

**Comment by artesim** [comment]
Hi, I had a quick look when you opened it, and the thing that had jumped at me was "lattitude" : I'm not native, so I may be mistaken, but I'm pretty sure it's a typo for "latitude".
But I'm available again this week-end, so I'll have a closer look.

**Comment by girotobial** [comment]
> [snip]thing that had jumped at me was "lattitude" : I'm not native, so I may be mistaken, but I'm pretty sure it's a typo for "latitude".

Yep you're right, it should be "latitude"

**Comment by artesim** [comment]
Hi, so I finally had time to look at it.
I like the direction you take, and although it will probably take some work to finish it, I think it's worth it.
I also like the result of your black formatter : I was afraid it would do weird things, but IMO it looks clean and readable.
As for the risk of regression in that kind of refactoring, I'm not sure if writing tests beforehand is a good idea, because by the time this branch is done, we may very well have to also rewrite them... (or not, I don't know).

**Comment by girotobial** [comment]
Config load issues resolved. Now ready to merge. @artesim

**Comment by chriskilding** [comment]
Now we've got CI enabled on the repo, it has run builds for existing PRs like this one. Sometimes it goes a bit weird on the first run; try pushing a trivial commit (e.g. 1-word change in readme) to this branch to re-run the build.

**Comment by chriskilding** [comment]
Also I notice there's a linter and some tests in this PR. It would be good to add linter and pytest runner steps to the CI build, so that they are checked automatically. Once this PR is merged, I'll open a new PR to enable those steps on the build.

**Comment by girotobial** [comment]
Ok I will make that change and see what comes of it.

**Comment by chriskilding** [comment]
Looking good - there's a green tick on the last commit

**Comment by chriskilding** [comment]
Hm... 

We're using the ubuntu 22.04 runner to get a modern version of GDAL (if it wasn't for GDAL, we could use any runner type). The 22.04 runners are very new, and GitHub said there might be a couple of teething problems.

Try another commit and see what happens?

**Comment by girotobial** [comment]
> We're using the ubuntu 22.04 runner to get a modern version of GDAL (if it wasn't for GDAL, we could use any runner type). 

So I found [here](https://github.com/actions/virtual-environments) that 22.04 is still in beta, so I tried downgrading but ran into the same issue you did with GDAL issues. I'm very tempted to disable the GDAL build for the time being just so we can start enforcing linting, and testing.

**Comment by chriskilding** [comment]
Yeah that's what I'm thinking too. I'll prepare a PR that takes out the GDAL build variant.

I'm presuming the GDAL code path is still optional in the dev branch? (In the original version it does a conditional `import gdal` in the relevant files.)

**Comment by chriskilding** [comment]
https://github.com/Ortho4XP/Ortho4XP/pull/47

**Comment by chriskilding** [comment]
After merging you'll of course want to rebase this branch to bring in the change from dev.

There is a rather useful GitHub repository setting you can turn on for this called "Always suggest updating pull request branches". This lets you auto-rebase and catch up with the base branch by clicking a single button in the PR. Screenshot of where to find it is attached.

github-repo-settings

**Comment by girotobial** [comment]
Sorted thank you.

**Pull request merged**
