### PR TITLE
Add pipenv and CI build

### PR DESCRIPTION
**Pull request by chriskilding**
This PR makes the minimum necessary modifications to (a) put a proper build tool around the project (pipenv), and (b) establish a CI build for it.

With these changes I was able to set up Ortho4XP in Pycharm using standard Pipenv project setup (i.e. `pipenv install`), launch the GUI, and build working scenery.

The only things that now need to be installed out-of-band are the native dependencies (gdal, spatialindex, p7zip).

If there is interest in merging this PR, I'll need to address a couple more things first:

- [ ] Update the README and install_mac.sh script in light of the different setup steps
- [ ] Get GDAL working. (I installed the GDAL native dependency, but when I tried to install the GDAL Python library it bounced me out with an error. Ideally I'd like to fix this before merging.)
- [ ] Use `importlib` to fix the handling of the resources in the Utils directory. (Currently Ortho4XP accesses those files with fragile relative path lookups; these make it impossible to write unit tests, since the tests do not use the project root as their working directory.)

### CODE REVIEW

**Comment by chriskilding** [comment]
This PR is along vaguely similar lines as https://github.com/Ortho4XP/Ortho4XP/pull/32. However I believe that PR tried to make too many changes at once, which made it difficult to merge.

By contrast, this PR does the minimum to put a standard project scaffold around Ortho4XP: it does not modify the application code except to make imports work. With fewer changes, it should be easier to merge. Code cleanup can then follow in future PRs.

**Comment by chriskilding** [comment]
The eventual aim should be to get Ortho4XP to a point where it's easy to produce standalone application packages of it (e.g. `.app` on Mac for the GUI or `.pkg` for the CLI), or at least make it possible to obtain it with `brew install ortho4xp`. That way, its users will no longer have to check it out from source or have to care about installing dependencies themselves.

This PR is intended to be the first step down that road.

**Comment by girotobial** [comment]
I like the CI build. Your right that  #32 tried to change too many things at once. I've left it there as a reference while certain commits have been cherry picked into dev. 

Re dependency management: I've already commited the change to poetry in the dev branch. 

Re GDAL: have you tried the dev branch install, i'd be interested in seeing if that resolves the issue?

I like the CI build, something I had in mind to change a while ago. Also the fix for the utils is most welcome. 

The other current challenge we are facing is the high level of coupling between files due to the way, in part, that the config files are loaded.

**Comment by chriskilding** [comment]
I found the fix to GDAL shortly after: I needed to ensure that the Python GDAL wrapper version was exactly the same as the system GDAL library version - once I set that correctly, the install worked. I also found a way to run the CI build in matrix form, with the GDAL extension present and absent; this should be helpful for test coverage.

Interestingly, in the scenery I generated with GDAL turned on, there were no buildings in the overlay. (Whereas there are buildings in the scenery I generated with GDAL off.) I'm not sure if this is a bug in the GDAL code pathway (in the master branch), or if it's down to some other configuration error.

**Comment by chriskilding** [comment]
I'm not attached to Pipenv, so I can rework the PR to use the Poetry definition from the dev branch.

Should I continue to base the PR on master, or should it be against dev?

**Comment by girotobial** [comment]
If you could base it on dev that would be great.

**Comment by chriskilding** [comment]
Ok, started a new PR #43 for this.

The new PR will do the minimum to add a CI build to the dev branch.

**Pull request closed without merging**
